from login import login
from download_material import download_material
from download_material import download_material_from_url
from download_course import download_course

import settings
import initialSetup
